name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Set GOFLAGS to use vendor directory
        run: echo "GOFLAPS=-mod=vendor" >> $GITHUB_ENV

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Install Dependencies
        run: go mod tidy && go mod vendor

      - name: Run Formatting Check
        run: test -z $(go fmt ./...)
      
      - name: Run Tests
        run: go test -cover ./... -v

      - name: Run Linting
        run: staticcheck ./...

